### ISSUE TITLE
centos 

### ISSUE THREAD

**Issue by agoodcoolman** [JeffHoogland/pyxhook#17]
/usr/bin/python2.7 /home/jin/PycharmProjects/python_android_utils/cf/liunx_monitor/example.py
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/home/jin/PycharmProjects/python_android_utils/cf/liunx_monitor/pyxhook.py", line 132, in run
    'client_died': True
  File "/usr/lib/python2.7/site-packages/Xlib/ext/record.py", line 121, in create_context
    ranges = ranges)
  File "/usr/lib/python2.7/site-packages/Xlib/protocol/rq.py", line 1418, in __init__
    self._binary = apply(self._request.to_binary, args, keys)
  File "/usr/lib/python2.7/site-packages/Xlib/protocol/rq.py", line 1103, in to_binary
    return apply(self.to_binary, varargs, keys)
  File "<string>", line 3, in to_binary
  File "/usr/lib/python2.7/site-packages/Xlib/protocol/rq.py", line 525, in pack_value
    data.append(self.type.pack_value(v))
  File "/usr/lib/python2.7/site-packages/Xlib/protocol/rq.py", line 1117, in pack_value
    return apply(self.to_binary, (), value)
  File "/usr/lib/python2.7/site-packages/Xlib/protocol/rq.py", line 1103, in to_binary
    return apply(self.to_binary, varargs, keys)
  File "<string>", line 4, in to_binary
  File "/usr/lib/python2.7/site-packages/Xlib/protocol/rq.py", line 575, in check_value
    v = f.check_value(val[i])
  File "/usr/lib/python2.7/site-packages/Xlib/protocol/rq.py", line 588, in check_value
    raise TypeError('Object value must be tuple, dictionary or DictWrapper: %s' % val)
TypeError: Object value must be tuple, dictionary or DictWrapper: 0

**Comment by agoodcoolman** [comment]
I hava installed newest [xlib](https://github.com/python-xlib/python-xlib/tree/master/examples) library,it work for me.

**Comment by Aareon** [comment]
@agoodcoolman, mind closing this issue.

Solution: Install the latest version of xlib
