### ISSUE TITLE
Bad Display Name

### ISSUE THREAD

**Issue by NET-OF-BEING** [JeffHoogland/pyxhook#26]
I can't get this running. ive used pip to install the pyxhook module and tried using both python 2.7 and 3.6.5.

Traceback (most recent call last):
  File "keylog.py", line 25, in <module>
    hookman = pyxhook.HookManager()
  File "/usr/local/lib/python3.6/site-packages/pyxhook/pyxhook.py", line 67, in __init__
    self.local_dpy = display.Display()
  File "/usr/local/lib/python3.6/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/local/lib/python3.6/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/local/lib/python3.6/site-packages/Xlib/protocol/display.py", line 85, in __init__
    name, protocol, host, displayno, screenno = connect.get_display(display)
  File "/usr/local/lib/python3.6/site-packages/Xlib/support/connect.py", line 73, in get_display
    return mod.get_display(display)
  File "/usr/local/lib/python3.6/site-packages/Xlib/support/unix_connect.py", line 61, in get_display
    raise error.DisplayNameError(display)
Xlib.error.DisplayNameError: Bad display name ""

Can someone help me with this please

**Comment by JeffHoogland** [comment]
Based on this message it looks like the error is coming from your XLib module and not pyxhook?

**Comment by leocotes** [comment]
I'm with the same problem...
I installed apt-get install python3-xlib and python-xlib

**Comment by JeffHoogland** [comment]
What version of xlib are you folks using and on what platform?

**Comment by leocotes** [comment]
python3-xlib             0.20-3
Ubuntu 18.04

**Comment by inmotions** [comment]
How should this problem be solved?

**Comment by Mr-Meowmix** [comment]
I am currently experiencing the same problem myself. On (manjaro) linux my program runs fine but if its on windows this error is thrown
